site_name: HSR Notizen FS18
site_url: https://doc.robinsuter.ch
repo_url: https://github.com/Excape/hsr-docs-fs18
site_description: HSR Study Documentation FS18
site_author: Robin Suter
copyright: 'Copyright (c) 2018 Robin Suter'

theme: 'material'

pages:
    - Home: 'index.md'
    - Playground: 'playground.md'
    - Cloud Solutions:
        - Index: 'clou/index.md'
        - Introduction: 'clou/introduction.md'
    - Compilerbau:
        - Index: 'combau/index.md'
        - Syntax: 'combau/syntax.md'
    - Deep Learning:
        - Index: 'dl/index.md'
        - Linear Algebra: 'dl/linear_algebra.md'

markdown_extensions:
  - toc(permalink=true)
  - sane_lists
  - admonition
  - mdx_math
  - codehilite(linenums=true)
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols

extra:
    palette:
        primary: 'yellow'
        accent: 'amber'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        github: 'excape'
        twitter: 'robin_suter'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_SVG

extra_css: [extra.css]
